networks:
  default_dev:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.5.0/24
      driver: default
services:
  Database:
    build:
      context: .
      dockerfile: DockerfileDatabase
    container_name: Trading_Database_Dev
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword
    image: trading_database_dev:5.7.20
    networks:
      default_dev:
        ipv4_address: "172.20.5.2"
    ports:
      - "53306:3306"
    restart: always
    volumes:
      - /var/lib/Trading_dev/Database:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping --silent"]
      interval: 1m
      timeout: 10s
      retries: 3
  SeleniumChrome:
    build:
      context: .
      dockerfile: DockerfileSeleniumChrome
    container_name: Trading_SeleniumChrome_Dev
    image: trading_seleniumchrome_dev:latest
    networks:
      default:
        ipv4_address: "172.20.1.3"
    ports:
      - "14443:4444"
    volumes:
      - /dev/shm:/dev/shm
    restart: always
  TradingCore:
    build:
      context: .
      dockerfile: DockerfileTradingCore
    container_name: Trading_TradingCore_Dev
    image: trading_tradingcore_dev:latest
    networks:
      default_dev:
        ipv4_address: "172.20.5.3"
    ports:
      - "583:80"
    volumes:
      - /var/lib/Trading_dev/TradingCore:/var/lib/Trading/TradingCore
    restart: always
  DataScraper:
    build:
      context: .
      dockerfile: DockerfileDataScraper
    container_name: Trading_DataScraper_Dev
    image: trading_datascraper_dev:latest
    networks:
      default_dev:
        ipv4_address: "172.20.5.4"
    ports:
      - "584:80"
    volumes:
      - /var/lib/Trading_dev/DataScraper:/var/lib/Trading/DataScraper
    restart: always
version: '3.0'
